# Generated by Django 3.2 on 2022-02-20 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_name_comment_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='name',
        ),
    ]
